describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://www.drom.ru/')
    cy.get('.css-xlo28g').click()
    cy.visit('https://www.drom.ru/')
    cy.get('.css-c96isf').click()
    cy.visit('https://www.drom.ru/')
    cy.get('[data-ga-stats-name="topmenu_sales"]').click()
    cy.visit('https://www.drom.ru/')
    cy.get('[data-ga-stats-name="topmenu_spec"]').click()
    cy.visit('https://www.drom.ru/')
    cy.get('[data-ga-stats-name="topmenu_baza"]').click()
    cy.visit('https://www.drom.ru/')
    cy.get('[data-ga-stats-name="topmenu_reviews"]').click()
    cy.visit('https://www.drom.ru/')
    cy.get('[data-ga-stats-name="topmenu_catalog_new"]').click()
    cy.visit('https://www.drom.ru/')
    cy.get('.css-4rcrui').click()
    cy.visit('https://www.drom.ru/')
    cy.get('.css-nxh0g4').click()
    cy.visit('https://www.drom.ru/')
    cy.get('.css-1h9spzo').click()
    cy.visit('https://www.drom.ru/')
    cy.get('[href="https://tver.drom.ru/acura/rdx/48222918.html"] > .css-1j9bceh').click()
    cy.visit('https://www.drom.ru/')
    cy.get(':nth-child(1) > :nth-child(1) > .css-1q61nn > .css-1q66we5').click()
    cy.visit('https://www.drom.ru/')
    cy.get('[data-ga-stats-name="widgetNeweconom"] > .css-4smrj6 > .css-1m8odau').click()
    cy.visit('https://www.drom.ru/')
    cy.get('[href="https://www.drom.ru/reviews/toyota/mark_x/1437640/"] > .css-8cc7j0 > .css-15y98p8 > .css-qy78xy').click()
    cy.visit('https://www.drom.ru/')
    cy.get(':nth-child(1) > .css-1hw028b > .css-uf6rlw').click()
    cy.visit('https://www.drom.ru/')
    cy.get(':nth-child(14) > .css-62s4al > :nth-child(1) > .css-10vgmnw > :nth-child(1) > .css-2zoxx4').click()
    cy.visit('https://www.drom.ru/')
    cy.get('.css-1lkf11s > :nth-child(1) > :nth-child(1) > .e8vftt60').click()
    cy.visit('https://www.drom.ru/')
    cy.get('.css-1kpqr6e').click()
    cy.visit('https://www.drom.ru/')
    cy.get('[href="https://www.drom.ru/about/press/"]').click()
    cy.visit('https://www.drom.ru/')
  })
})